---
title             : "Registered Report: Researcher's Perceptions of Social Dynamics and Attitudes about Open Science "
shorttitle        : "Social Dynamics Open Science"

author: 
  - name          : "Ashley J Thomas"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "43 Vassar, Cambridge"
    email         : "ajthomas@mit.edu"
    role:         # Contributorship roles (e.g., CRediT, https://casrai.org/credit/)
      - "Conceptualization"
      - "Writing - Original Draft Preparation"
      - "Writing - Review & Editing"
  - name          : "Rebecca Saxe"
    affiliation   : "1,2"
    role:
      - "Writing - Review & Editing"
      - "Supervision"

affiliation:
  - id            : "1"
    institution   : "MIT"
  - id            : "2"
    institution   : "CREOS"


abstract:  When people join new groups, they must learn about the relevent social dynamics or 'rules of engagement' within those groups. Here we ask if academic researchers have intuitive thoeries about the social dynamics of their field. Next we ask if these intuitive theories correspond to decisions to engage in open science. Study 1, was an survey open to all academic researchers. We found that researchers did think about the social dynamics in their field and that these attitudes did not laod onto warmth and competence. Study 2 was open to all researchers in MIT's school of science. We replicated the findings from Study 1 and in exploratory analyses, asked whether these attitudes corresponded to open science practices. We did not find consistent evidence that the way people think about the social dynamics of their field correspond to the their attitudes toward nor engagment with open science practices. Study 3 was a representative sample from the School of Science at MIT. Here we will repeat the analyses conducted in Study 2.

  <!-- https://tinyurl.com/ybremelq -->
  
keywords          : "keywords"
wordcount         : "X"

bibliography      : "r-references.bib"

floatsintext      : no
linenumbers       : yes
draft             : no
mask              : no

figurelist        : no
tablelist         : no
footnotelist      : no

classoption       : "man"
output            : papaja::apa6_pdf
---

```{r setup, include = FALSE}
library("papaja")
r_refs("r-references.bib")
```

```{r analysis-preferences}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```

# Methods

We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study. <!-- 21-word solution (Simmons, Nelson & Simonsohn, 2012; retrieved from http://ssrn.com/abstract=2160588) -->

## Participants

## Material

## Procedure

## Data analysis

We used `r cite_r("r-references.bib")` for all our analyses.

# Results

# Discussion

\newpage

# References

::: {#refs custom-style="Bibliography"}
:::
